NewPR
peterbean410/datorum-java pull request #3
Opened 2024-08-04 11:52 UTC by Wibulization

2024-08-06 06:11 UTC, peterbean410 commented on engine/specs-java/steps/schema/DatabaseDefinitionSteps.java
> +        dropSchemaIfExist();
```suggestion
        dropSchemaIfExists();
```

2024-08-06 06:12 UTC, peterbean410 commented on engine/specs-java/steps/schema/DatabaseDefinitionSteps.java
> +    public void aSchemaWithATable() throws Exception {
```suggestion
    public void aPostgresDatabaseWithoutSchemas() throws Exception {
```

2024-08-06 06:12 UTC, peterbean410 commented on engine/specs-java/steps/schema/DatabaseDefinitionSteps.java
> +        schema = implementationOfSchema();
As discussed

2024-08-06 06:13 UTC, peterbean410 commented on engine/specs-java/steps/schema/DatabaseDefinitionSteps.java
> +        checkSchemaExist();
Let's put schemaName as a string param here

2024-08-06 06:14 UTC, peterbean410 commented on engine/specs-java/io/beandev/datorum/CreatePostgres.java
> +    }
Let's put 1 minute as TIMEOUT

2024-08-06 06:17 UTC, peterbean410 requested changes
Let's also update the Makefile to add `test-engine` rule such that it will run the test for `engine` Gradle sub project.

2024-08-06 09:06 UTC, Wibulization commented on engine/specs-java/steps/schema/DatabaseDefinitionSteps.java
> +        schema = implementationOfSchema();
![image](https://github.com/user-attachments/assets/a2a6fb9c-adcd-4e89-8fe2-eec7199fc985)

2024-08-06 09:06 UTC, Wibulization commented on engine/specs-java/steps/schema/DatabaseDefinitionSteps.java
> +        checkSchemaExist();
![image](https://github.com/user-attachments/assets/ff12e587-993b-40a7-a643-f66af4af80a9)

2024-08-06 09:07 UTC, Wibulization commented on engine/specs-java/io/beandev/datorum/CreatePostgres.java
> +    }
![image](https://github.com/user-attachments/assets/b5a4e67e-840d-4568-85a5-6bb937cafe9f)

2024-08-06 09:08 UTC, Wibulization commented
> Let's also update the Makefile to add `test-engine` rule such that it will run the test for `engine` Gradle sub project.
![image](https://github.com/user-attachments/assets/37e5c2b5-8d83-4569-951d-7930fe1a74a4)

2024-08-06 09:15 UTC, Wibulization commented on engine/specs-java/steps/schema/DatabaseDefinitionSteps.java
> +        checkSchemaExist();
Change datorum_schema to word expression to get the name of schema. Then we get schemaName as a parameter of method checkSchemaExist()

2024-08-06 09:16 UTC, Wibulization commented on engine/specs-java/steps/schema/DatabaseDefinitionSteps.java
> +        checkSchemaExist();
Here is the method checkSchemaExist when it has parameter
![image](https://github.com/user-attachments/assets/5e977b67-fcff-4934-aa20-fd97d4c8892d)

2024-08-06 09:20 UTC, Wibulization commented on engine/specs-java/steps/schema/DatabaseDefinitionSteps.java
> +        schema = implementationOfSchema();
We don't need the method implementationOfSchema to create schema repository, we just create it directly

2024-08-06 09:22 UTC, Wibulization commented on engine/specs-java/steps/schema/DatabaseDefinitionSteps.java
> +    public void aSchemaWithATable() throws Exception {
Change the name of the method

2024-08-06 09:23 UTC, Wibulization commented on engine/specs-java/steps/schema/DatabaseDefinitionSteps.java
> +        dropSchemaIfExist();
Change the name of the method

2024-08-06 09:31 UTC, Wibulization commented on engine/specs-java/steps/schema/DatabaseDefinitionSteps.java
> +        dropSchemaIfExist();
![image](https://github.com/user-attachments/assets/73eba34f-e04f-4518-a513-4de176b5fd79)
![image](https://github.com/user-attachments/assets/67c8659c-9224-43ee-bf08-4a0b26f7e1fb)

2024-08-06 09:32 UTC, Wibulization commented on engine/specs-java/steps/schema/DatabaseDefinitionSteps.java
> +    public void aSchemaWithATable() throws Exception {
![image](https://github.com/user-attachments/assets/0ec98596-eab4-4c3c-bcd4-15a6ecacc2be)

2024-08-07 06:30 UTC, Wibulization commented on engine/specs-java/io/beandev/datorum/CreatePostgres.java
> +    }
![image](https://github.com/user-attachments/assets/a104a744-2cbe-4fed-9878-e7cb1f0e795f)

2024-08-07 17:00 UTC, peterbean410 commented on engine/specs-java/io/beandev/datorum/CreatePostgres.java
> +        waitForPodReady(api, "default", "postgres");
Check again and remove all unnecessary comments, try to name the method as clear and descriptive as possible.

2024-08-07 17:02 UTC, peterbean410 commented on engine/specs-java/io/beandev/datorum/CreatePostgres.java
> +                V1Service createdService = api.createNamespacedService(namespace, service, null, null, null, null);
Which line actually creates the service ? L170 or L171?

If L170 does not actually create the service, why did you name it `createService()` ?

2024-08-08 03:40 UTC, Wibulization commented on engine/specs-java/io/beandev/datorum/CreatePostgres.java
> +        waitForPodReady(api, "default", "postgres");
![image](https://github.com/user-attachments/assets/4b927b79-0d48-4d80-bea1-8b58135f7013)

2024-08-08 03:41 UTC, Wibulization commented on engine/specs-java/io/beandev/datorum/CreatePostgres.java
> +                V1Service createdService = api.createNamespacedService(namespace, service, null, null, null, null);
![image](https://github.com/user-attachments/assets/2db31390-fec6-436c-99c4-44e09d4dac5b)

2024-08-08 05:19 UTC, Wibulization commented on engine/specs-java/io/beandev/datorum/CreatePostgres.java
> +                V1Service createdService = api.createNamespacedService(namespace, service, null, null, null, null);
![image](https://github.com/user-attachments/assets/8dbf8c03-2edb-4555-ba68-11b60d685ee5)

2024-08-09 04:25 UTC, peterbean410 commented on engine/specs-java/io/beandev/datorum/CreatePostgres.java
> +                V1Pod podBody = podBody();
```suggestion
                V1Pod postgresPodDef = podBody();
```

2024-08-09 04:33 UTC, Wibulization commented on engine/specs-java/io/beandev/datorum/CreatePostgres.java
> +                V1Pod podBody = podBody();
![image](https://github.com/user-attachments/assets/feff6e15-454a-4cf9-b3ee-50f115ec4acc)

2024-08-09 05:01 UTC, peterbean410 commented on engine/specs-java/steps/schema/DatabaseDefinitionSteps.java
> +        Assertions.assertNotNull(jdbcSchemaRepository, "JdbcSchemaRepository should not null");
```suggestion
```
Are you trying it test if Java `new` keyword works?

2024-08-09 05:01 UTC, peterbean410 commented on engine/specs-java/steps/schema/DatabaseDefinitionSteps.java
> +    private void dropSchemaIfExists() {
```suggestion
    private void dropSchemaIfExists(schema: String) {
```

2024-08-09 05:03 UTC, peterbean410 commented on engine/specs-java/io/beandev/datorum/CreatePostgres.java
> +    private static void ensureServiceExists(CoreV1Api api, String namespace, String serviceName)
ensure what service ?

2024-08-09 05:03 UTC, peterbean410 commented on engine/src/testUnit/java/io/beandev/datorum/migration/MigratorTest.java
> +    }
???????

2024-08-09 05:16 UTC, Wibulization commented on engine/src/testUnit/java/io/beandev/datorum/migration/MigratorTest.java
> +    }
![image](https://github.com/user-attachments/assets/5665e35d-7c6c-45e0-8a19-fbe2a5adf9e9)
Remove unnecessary test

2024-08-09 05:16 UTC, Wibulization commented on engine/specs-java/io/beandev/datorum/CreatePostgres.java
> +    private static void ensureServiceExists(CoreV1Api api, String namespace, String serviceName)
![image](https://github.com/user-attachments/assets/1cddf9e7-75b5-419f-9191-84a8c93091aa)

2024-08-09 05:16 UTC, Wibulization commented on engine/specs-java/steps/schema/DatabaseDefinitionSteps.java
> +    private void dropSchemaIfExists() {
![image](https://github.com/user-attachments/assets/9dc34129-8b54-4ce7-8574-23c28d0c61ff)
Method
![image](https://github.com/user-attachments/assets/8f418c74-82f9-4d5f-9028-4343df255991)

2024-08-09 05:16 UTC, Wibulization commented on engine/specs-java/steps/schema/DatabaseDefinitionSteps.java
> +        Assertions.assertNotNull(jdbcSchemaRepository, "JdbcSchemaRepository should not null");
![image](https://github.com/user-attachments/assets/6908cdba-8e73-4612-bc38-3c52742480de)

2024-08-16 05:31 UTC, peterbean410 approved these changes

2024-08-16 06:07 UTC, merged